FROM    centos:centos7
COPY    hinemos-6.2-manager-6.2.2-1.el7.x86_64.rpm /tmp/
COPY    hinemos-6.2-web-6.2.2-1.el7.x86_64.rpm /tmp/
RUN     yum -y install \
        java-1.8.0-openjdk \
        java-1.8.0-openjdk-devel \
        lsof net-tools \
        net-snmp \
        net-snmp-utils \
        nmap \
        sudo \
        sysstat \
        tcpdump \
        unzip \
        vim-common \
        vlgothic-p-fonts \
        wsmancli && \
        rm -rf /var/cache/yum/* && \
        yum clean all
RUN     localedef -f UTF-8 -i ja_JP ja_JP.UTF-8 && \
        localedef --list-archive | egrep --invert-match --ignore-case "^(ja|en_US)" \
        | xargs localedef --delete-from-archive && \
        mv --force /usr/lib/locale/locale-archive{,.tmpl} && \
        build-locale-archive --verbose && \
        ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
ENV     LANG="ja_JP.UTF-8" \
        LANGUAGE="ja_JP:ja" \
        LC_ALL="ja_JP.UTF-8" \
        TZ="Asia/Tokyo"
RUN     rpm -ivh /tmp/hinemos-6.2-manager-6.2.2-1.el7.x86_64.rpm && \
        rpm -ivh /tmp/hinemos-6.2-web-6.2.2-1.el7.x86_64.rpm
RUN     echo -n \
        $'#!/bin/sh\n\
        sudo -u hinemos /opt/hinemos/postgresql/bin/pg_ctl start \
        -D /opt/hinemos/var/data/ \
        -l /opt/hinemos/postgresql/bin/logfile\n\
        wait\n\
        /opt/hinemos/bin/jvm_start.sh\n\
        wait\n\
        /opt/hinemos_web/bin/tomcat_start.sh\n\
        wait\n\ 
        ' > /home/start.sh
CMD     ["/bin/bash"]
