version: '3'

services:
  hinemos-6.2-manager:
    image: akatoan/hinemos-6.2-manager:v5
    user: root
    container_name: hinemos-6.2-manager
    hostname: hinemos-6.2-manager
    command: /sbin/init
    privileged: true
    stdin_open: true
    tty: true
    networks:
      hinemos_network:
        ipv4_address: 10.244.0.2
    restart: always
    ports:
      - 88:80

  hinemos-6.2-agent:
    image: akatoan/hinemos-6.2-agent:v5
    user: root
    container_name: hinemos-6.2-agent01
    hostname: h-agent01
    command: /sbin/init
    privileged: true
    stdin_open: true
    tty: true
    networks:
      hinemos_network:
        ipv4_address: 10.244.0.3
    restart: always
    depends_on:
      - hinemos-6.2-manager

networks:
  hinemos_network:
    driver: bridge
    name: hinemos_network
    ipam:
      driver: default
      config:
        - subnet: 10.244.0.0/24