FROM    centos:centos7
COPY    hinemos-6.2-agent-6.2.2-1.el.noarch.rpm /tmp/
RUN     yum -y install \
        java-1.8.0-openjdk \
        openssh-clients \
        net-snmp \
        net-snmp-libs \
        net-snmp-utils \
        nmap \
        rsyslog && \
        rm -rf /var/cache/yum/* && \
        yum clean all
RUN     localedef -f UTF-8 -i ja_JP ja_JP.UTF-8 && \
        localedef --list-archive | egrep --invert-match --ignore-case "^(ja|en_US)" \
        | xargs localedef --delete-from-archive && \
        mv --force /usr/lib/locale/locale-archive{,.tmpl} && \
        build-locale-archive --verbose && \
        ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
ENV     LANG="ja_JP.UTF-8" \
        LANGUAGE="ja_JP:ja" \
        LC_ALL="ja_JP.UTF-8" \
        TZ="Asia/Tokyo"
RUN     HINEMOS_MANAGER=10.244.0.2 rpm -ivh /tmp/hinemos-6.2-agent-6.2.2-1.el.noarch.rpm
RUN     echo -n \
        $'#!/bin/sh\n\
        /opt/hinemos_agent/bin/agent_start.sh\n\
        wait\n\ 
        ' > /home/start.sh
CMD     ["/bin/bash"]
